name: Elixir CI

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**/*.md"
      - ".editorconfig"
      - ".gitignore"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**/*.md"
      - ".editorconfig"
      - ".gitignore"

env:
  MIX_ENV: test

permissions:
  contents: read

jobs:
  test:
    name: Run Mix Tests
    runs-on: ubuntu-latest

    steps:
      - name: Setup Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: "1.14"
          otp-version: "25"

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache deps
        id: cache-deps
        uses: actions/cache@v3
        env:
          cache-name: cache-elixir-deps
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.cache-name }}-

      - name: Cache compiled build
        id: cache-build
        uses: actions/cache@v3
        env:
          cache-name: cache-compiled-build
        with:
          path: _build
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.cache-name }}-
            ${{ runner.os }}-mix-

      - name: Install dependencies
        run: mix deps.get

      - name: Compiles without warnings
        run: mix compile --warnings-as-errors

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Run Credo Check
        run: mix credo

      - name: Run Tests
        run: mix test
